version: '2.1'

services:
    postgres:
        image: postgres:17.0
        hostname: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file: "./.env"
